# To set display variable, type the following in your command line depending on OS
# Windows: $env:DISPLAY="<YOUR_IP>:0.0"
# Linux: export DISPLAY="<YOUR_IP>:0.0"
services:
  git: 
    build: ./GitDocker
    image: gitdocker
    environment: 
      - DISPLAY=$DISPLAY
    volumes:
      - ./MicroServices:/root
  ibm: 
    build: ./IBMSASDocker
    image: ibmsasdocker
    environment: 
      - DISPLAY=$DISPLAY
    volumes:
      - ./MicroServices:/root
  jupyter: 
    build: ./JupyterDocker
    image: jupyterdocker
    environment: 
      - DISPLAY=$DISPLAY
    volumes:
      - ./MicroServices:/root
  markdown: 
    build: ./MarkdownDocker
    image: markdowndocker
    environment: 
      - DISPLAY=$DISPLAY
    volumes:
      - ./MicroServices:/root
  orange: 
    build: ./OrangeDocker
    image: orangedocker
    environment: 
      - DISPLAY=$DISPLAY
    volumes:
      - ./MicroServices:/root
  pyspark: 
    build: ./PySparkDocker
    image: pysparkdocker
    environment: 
      - DISPLAY=$DISPLAY
    volumes:
      - ./MicroServices:/root
  rstudio: 
    build: ./RStudioDocker
    image: rstudiodocker
    environment: 
      - DISPLAY=$DISPLAY
    volumes:
      - ./MicroServices:/root
  sonarcloud: 
    build: ./SonarCloudDocker
    image: sonarclouddocker
    environment: 
      - DISPLAY=$DISPLAY
    volumes:
      - ./MicroServices:/root
  tableau: 
    build: ./TableauDocker
    image: tableaudocker
    environment: 
      - DISPLAY=$DISPLAY
    volumes:
      - ./MicroServices:/root
  tensorflow: 
    build: ./TensorflowDocker
    image: tensorflowdocker
    environment: 
      - DISPLAY=$DISPLAY
    volumes:
      - ./MicroServices:/root
  spyder: 
    build: ./SpyderDocker
    image: spyderdocker
    environment: 
      - DISPLAY=$DISPLAY
    volumes:
      - ./MicroServices:/root
  vscode: 
    build: ./VSCodeIDEDocker
    environment:
      - DONT_PROMPT_WSL_INSTALL=1
    image: vscodedocker
    environment: 
      - DISPLAY=$DISPLAY
    volumes:
      - ./MicroServices:/root
  hadoop: 
    build: ./HadoopDocker
    image: hadoopdocker
    environment: 
      - DISPLAY=$DISPLAY
      - HADOOP_HOME=/usr/local/hadoop 
      - HADOOP_INSTALL=/usr/local/hadoop 
      - HADOOP_MAPRED_HOME=/usr/local/hadoop 
      - HADOOP_COMMON_HOME=/usr/local/hadoop 
      - HADOOP_HDFS_HOME=/usr/local/hadoop 
      - YARN_HOME=/usr/local/hadoop 
      - HADOOP_COMMON_LIB_NATIVE_DIR=/usr/local/hadoop/lib/native 
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/hadoop/sbin:/usr/local/hadoop/bin 
      - HADOOP_OPTS="-Djava.library.path=/usr/local/hadoop/lib/native"
      - HDFS_NAMENODE_USER=root
      - HDFS_DATANODE_USER=root
      - YARN_RESOURCEMANAGER_USER=root
      - YARN_NODEMANAGER_USER=root
      - HDFS_SECONDARYNAMENODE_USER=root
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
      - HADOOP_CLASSPATH+=\" /usr/local/hadoop/lib/*.jar\"
    volumes:
      - ./MicroServices:/root
  gui: 
    build: ./gui
    image: gui
    depends_on:
      - git
      - ibm
      - jupyter
      - markdown
      - orange
      - pyspark
      - rstudio
      - sonarcloud
      - spyder
      - tableau
      - tensorflow
      - vscode
      - hadoop
    environment: 
      - DISPLAY=$DISPLAY
    volumes: 
      - ./MicroServices:/root